"use client";

import { sendDesignAssetToLibraryAction } from "@/app/actions/asset-actions";
import type { ApiRecord } from "@/lib/api/_crud";
import { useMemo, useState, useTransition } from "react";
import { StorageImage } from "./storage-image";
import styles from "../record-manager.module.css";

type Props = { rows: ApiRecord[]; titleField: string; categoryField?: string; imageFields: string[]; canSendToLibrary?: boolean };

function images(row: ApiRecord, fields: string[]) {
  const result: string[] = [];
  for (const field of fields) {
    const value = row[field];
    if (Array.isArray(value)) result.push(...value.map(String).filter(Boolean));
    else if (typeof value === "string" && value) { try { const parsed=JSON.parse(value); if(Array.isArray(parsed))result.push(...parsed.map(String).filter(Boolean)); else result.push(value); } catch { result.push(value); } }
  }
  return [...new Set(result)];
}
function display(value:unknown){if(value===null||value===undefined||value==="")return"";if(Array.isArray(value))return value.map((item)=>typeof item==="object"?JSON.stringify(item):String(item)).join(" - ");if(typeof value==="object")return JSON.stringify(value);return String(value);}
function labels(value:unknown){if(Array.isArray(value))return value.map(String);if(typeof value==="string"){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[];}catch{return value.split(",").map((item)=>item.trim()).filter(Boolean);}}return[];}

export function AssetGallery({ rows, titleField, categoryField, imageFields, canSendToLibrary = false }: Props) {
  const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [secondary,setSecondary]=useState("");const [label,setLabel]=useState("");const [sort,setSort]=useState("newest");const [message,setMessage]=useState("");const [transferId,setTransferId]=useState("");const [selectedId,setSelectedId]=useState("");const [imageIndex,setImageIndex]=useState(0);const [pending,startTransition]=useTransition();
  const categories=categoryField?[...new Set(rows.map((row)=>String(row[categoryField]||"Uncategorized")))].sort():[];
  const secondaryField=rows.some((row)=>row.jenis)?"jenis":rows.some((row)=>row.tipe)?"tipe":"";const secondaryOptions=secondaryField?[...new Set(rows.map((row)=>String(row[secondaryField]||"Unknown")))].sort():[];const labelOptions=[...new Set(rows.flatMap((row)=>labels(row.labels)))].sort();
  const visible=useMemo(()=>rows.filter((row)=>(!query||`${row[titleField]} ${categoryField?row[categoryField]:""} ${row.copywriting||""}`.toLowerCase().includes(query.toLowerCase()))&&(!category||String(categoryField?row[categoryField]:"")===category)&&(!secondary||String(row[secondaryField])===secondary)&&(!label||labels(row.labels).includes(label))).sort((a,b)=>sort==="likes"?Number(b.likes||0)-Number(a.likes||0):sort==="views"?Number(b.views||0)-Number(a.views||0):String(b.created_at||"").localeCompare(String(a.created_at||""))),[rows,query,category,secondary,label,sort,titleField,categoryField,secondaryField]);
  function sendToLibrary(formData:FormData){const id=transferId;setMessage("");startTransition(async()=>{try{await sendDesignAssetToLibraryAction(id,Object.fromEntries(formData.entries()));setMessage("Asset added to the content library.");setTransferId("");}catch(error){setMessage(error instanceof Error?error.message:"Asset could not be copied.");}});}
  const transfer=rows.find((row)=>String(row.id)===transferId);const selected=rows.find((row)=>String(row.id)===selectedId);const selectedImages=selected?images(selected,imageFields):[];
  return <div className={styles.toolStack}><div className={styles.filterBar}><input placeholder="Search gallery" value={query} onChange={(event)=>setQuery(event.target.value)}/>{categoryField?<select value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">All categories</option>{categories.map((value)=><option key={value}>{value}</option>)}</select>:null}{secondaryField?<select value={secondary} onChange={(event)=>setSecondary(event.target.value)}><option value="">All types</option>{secondaryOptions.map((value)=><option key={value}>{value}</option>)}</select>:null}{labelOptions.length?<select value={label} onChange={(event)=>setLabel(event.target.value)}><option value="">All labels</option>{labelOptions.map((value)=><option key={value}>{value}</option>)}</select>:null}<select value={sort} onChange={(event)=>setSort(event.target.value)}><option value="newest">Newest</option><option value="likes">Most liked</option><option value="views">Most viewed</option></select>{message?<span className={styles.formMessage}>{message}</span>:null}</div><div className={styles.galleryGrid}>{visible.map((row)=>{const rowImages=images(row,imageFields);return <article key={String(row.id)}><button className={styles.galleryPreview} onClick={()=>{setSelectedId(String(row.id));setImageIndex(0);}}>{rowImages[0]?<StorageImage objectKey={rowImages[0]} label={String(row[titleField]||"Asset")}/>:<div className={styles.storageImage}><i className="ti ti-photo-off"/></div>}{rowImages.length>1?<span className={styles.imageCount}><i className="ti ti-library-photo"/> {rowImages.length}</span>:null}</button><div><strong>{String(row[titleField]||"Untitled")}</strong><div className={styles.galleryPills}>{categoryField?<span>{String(row[categoryField]||"Uncategorized")}</span>:null}{secondaryField?<span>{String(row[secondaryField]||"Unknown")}</span>:null}{labels(row.labels).slice(0,3).map((value)=><span key={value}>{value}</span>)}</div>{row.likes!==undefined||row.views!==undefined?<div className={styles.galleryStats}><span>{Number(row.likes||0).toLocaleString("id-ID")} likes</span><span>{Number(row.views||0).toLocaleString("id-ID")} views</span></div>:null}<footer>{row.link?<a href={String(row.link)} rel="noreferrer" target="_blank"><i className="ti ti-external-link"/> Source</a>:null}{canSendToLibrary?<button className={styles.secondaryButton} disabled={pending} onClick={()=>setTransferId(String(row.id))} type="button"><i className="ti ti-library-plus"/> Add to library</button>:null}</footer></div></article>;})}</div>{!visible.length?<div className={styles.emptyState}><i className="ti ti-photo-off"/><strong>No matching assets</strong></div>:null}
  {selected?<div className={styles.detailOverlay} onMouseDown={()=>setSelectedId("")}><article className={`${styles.detailPanel} ${styles.galleryDetail}`} onMouseDown={(event)=>event.stopPropagation()}><header><div><span>{categoryField?String(selected[categoryField]||"Uncategorized"):"Gallery item"}</span><h2>{String(selected[titleField]||"Untitled")}</h2></div><button onClick={()=>setSelectedId("")}><i className="ti ti-x"/></button></header>{selectedImages.length?<div className={styles.galleryCarousel}><StorageImage objectKey={selectedImages[imageIndex]} label={String(selected[titleField]||"Asset")}/>{selectedImages.length>1?<><button onClick={()=>setImageIndex((value)=>(value-1+selectedImages.length)%selectedImages.length)}><i className="ti ti-chevron-left"/></button><button onClick={()=>setImageIndex((value)=>(value+1)%selectedImages.length)}><i className="ti ti-chevron-right"/></button><span>{imageIndex+1} / {selectedImages.length}</span></>:null}</div>:null}<div className={styles.galleryMetadata}>{Object.entries(selected).filter(([key,value])=>!['id','created_at','updated_at',...imageFields].includes(key)&&display(value)).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{display(value)}</strong></div>)}</div></article></div>:null}
  {transfer?<section className={styles.createPanel}><div className={styles.workspaceHeader}><div><span className={styles.eyebrow}>Review library entry</span><h3>{String(transfer[titleField]||"Untitled")}</h3></div><button className={styles.secondaryButton} onClick={()=>setTransferId("")} type="button"><i className="ti ti-x"/> Cancel</button></div><form action={sendToLibrary} className={styles.formGrid}><label className={styles.field}><span>Platform</span><select name="platform"><option>Instagram</option><option>TikTok</option><option>YouTube</option><option>LinkedIn</option></select></label><label className={styles.field}><span>Content type</span><select name="jenis"><option>Carousel</option><option>Reels/Video</option><option>Single Image</option><option>Thread/Text</option></select></label><label className={styles.field}><span>Likes</span><input min="0" name="likes" required type="number"/></label><label className={styles.field}><span>Comments</span><input min="0" name="comments" type="number"/></label><label className={styles.field}><span>Shares</span><input min="0" name="shares" type="number"/></label><label className={styles.field}><span>Views</span><input min="0" name="views" type="number"/></label><label className={styles.field}><span>Copywriting</span><textarea defaultValue={String(transfer.nama||"")} name="copywriting"/></label><label className={styles.field}><span>Labels</span><input defaultValue={String(transfer.kategori||"")} name="labels"/></label><label className={styles.field}><span>Source URL</span><input defaultValue={String(transfer.link||"")} name="link"/></label><label className={styles.field}><span>Notes</span><textarea defaultValue={String(transfer.notes||"")} name="notes"/></label><button className={styles.primaryButton} disabled={pending}>Add to content library</button></form></section>:null}</div>;
}
