"use client";

import { createContentLibraryAssetAction, createDesignAssetAction } from "@/app/actions/asset-actions";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import styles from "../record-manager.module.css";

export function AssetUploadTools({mode}:{mode:"design"|"content"}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [pasted,setPasted]=useState<File[]>([]);const previews=useMemo(()=>pasted.map((file)=>URL.createObjectURL(file)),[pasted]);
  useEffect(()=>()=>previews.forEach(URL.revokeObjectURL),[previews]);
  function addFiles(files:File[]){setPasted((current)=>[...current,...files.filter((file)=>file.type.startsWith("image/"))].slice(0,12));}
  async function submit(formData:FormData){const selected=formData.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0);const files=[...selected,...pasted].slice(0,12);if(!files.length){setMessage("Select, drop, or paste at least one image.");return;}setBusy(true);setMessage("Uploading images...");try{const storagePaths:string[]=[];for(const file of files){const signed=await fetch("/api/storage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({area:"design-assets",filename:file.name||`pasted-${Date.now()}.png`,contentType:file.type})});const prepared=await signed.json() as {key?:string;url?:string;error?:string};if(!signed.ok||!prepared.key||!prepared.url)throw new Error(prepared.error||"Upload could not be prepared.");const uploaded=await fetch(prepared.url,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!uploaded.ok)throw new Error(`Upload failed for ${file.name}.`);storagePaths.push(prepared.key);}const labels=String(formData.get("labels")||"").split(",").map((item)=>item.trim()).filter(Boolean);const input=Object.fromEntries(formData.entries());delete input.files;if(mode==="design")await createDesignAssetAction({...input,storage_paths:storagePaths});else await createContentLibraryAssetAction({...input,labels,storage_paths:storagePaths});setMessage("Saved.");setPasted([]);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Upload failed.");}finally{setBusy(false);}}
  return <details className={styles.createPanel}><summary><i className="ti ti-photo-plus"/> Upload {mode==="design"?"design asset":"content reference"}</summary><form action={submit} className={styles.formGrid}>{mode==="design"?<><label className={styles.field}><span>Name</span><input name="nama" required/></label><label className={styles.field}><span>Category</span><input name="kategori" required/></label><label className={styles.field}><span>Type</span><select name="tipe"><option value="assets">Asset</option><option value="references">Reference</option></select></label></>:<><label className={styles.field}><span>Platform</span><select name="platform"><option>Instagram</option><option>TikTok</option><option>YouTube</option><option>LinkedIn</option></select></label><label className={styles.field}><span>Type</span><select name="jenis"><option>Carousel</option><option>Reels/Video</option><option>Single Image</option><option>Thread/Text</option></select></label><label className={styles.field}><span>Likes</span><input name="likes" required type="number"/></label><label className={styles.field}><span>Labels</span><input name="labels" placeholder="label, label"/></label><label className={styles.field}><span>Copywriting</span><textarea name="copywriting"/></label></>}<label className={styles.field}><span>Source URL</span><input name="link"/></label><label className={`${styles.field} ${styles.pasteUpload}`} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();addFiles([...event.dataTransfer.files]);}} onPaste={(event)=>addFiles([...event.clipboardData.files])} tabIndex={0}><span>Images</span><input accept="image/*" multiple name="files" type="file"/><small>Choose, drag, or paste images here. Up to 12.</small>{previews.length?<div>{previews.map((url,index)=><img alt={`Pasted ${index+1}`} key={url} src={url}/>)}</div>:null}</label><label className={styles.field}><span>Notes</span><textarea name="notes"/></label><button className={styles.primaryButton} disabled={busy}>{busy?"Uploading...":"Save"}</button>{message?<p className={styles.formMessage}>{message}</p>:null}</form></details>;
}
