"use client";

import { addCarouselPlanLinkAction, addStorySlideAction, setStoryPlanStatusAction } from "@/app/actions/content-planning-actions";
import type { ApiRecord } from "@/lib/api/_crud";
import Link from "next/link";
import type { ReactNode } from "react";
import { useMemo, useState, useTransition } from "react";
import { StorageImage } from "./storage-image";
import styles from "../record-manager.module.css";

type Tab="calendar"|"stories"|"carousels"|"directories"|"manage";
function day(value:unknown){return typeof value==="string"?value.slice(0,10):"";}

export function ContentPlanningTools({dates,stories,storyLinks,carousels,carouselLinks,ctas,kols,mtStories,management}:{dates:ApiRecord[];stories:ApiRecord[];storyLinks:ApiRecord[];carousels:ApiRecord[];carouselLinks:ApiRecord[];ctas:ApiRecord[];kols:ApiRecord[];mtStories:ApiRecord[];management:ReactNode}){
  const [tab,setTab]=useState<Tab>("calendar");const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));const [pending,startTransition]=useTransition();
  const monthDate=useMemo(()=>new Date(`${month}-01T00:00:00`),[month]);const calendarDays=useMemo(()=>{const start=new Date(monthDate);start.setDate(1-start.getDay());return Array.from({length:42},(_,index)=>{const value=new Date(start);value.setDate(start.getDate()+index);return value;});},[monthDate]);
  const visibleDates=dates.filter((row)=>!month||day(row.tanggal).startsWith(month));const visibleCarousels=carousels.filter((row)=>!month||day(row.tanggal_posting).startsWith(month));
  return <div className={styles.contentPlanningWorkspace}><div className={styles.workspaceHeader}><div><p>Marketing</p><h1>Content planning</h1><span>Date-grouped Story slides, Carousel briefs, publishing status, reusable links, KOLs, and MT Story candidates.</span></div><input aria-label="Planning month" type="month" value={month} onChange={(event)=>setMonth(event.target.value)}/></div><div className={styles.metricStrip}><div><strong>{dates.length}</strong><span>Story dates</span></div><div><strong>{stories.length}</strong><span>Story slides</span></div><div><strong>{carousels.length}</strong><span>Carousels</span></div><div><strong>{kols.length}</strong><span>KOL profiles</span></div><div><strong>{mtStories.filter((row)=>!row.is_posted).length}</strong><span>MT stories pending</span></div></div><nav className={styles.workspaceTabs}>{([['calendar','Calendar'],['stories','Story planner'],['carousels','Carousel planner'],['directories','KOL & MT Story'],['manage','Create & manage']] as const).map(([key,label])=><button className={tab===key?styles.workspaceTabActive:styles.workspaceTab} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  {tab==="calendar"?<section className={styles.calendarPanel}><header><div><h2>Publishing calendar</h2><span>{monthDate.toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</span></div></header><div className={styles.monthCalendar}>{calendarDays.map((date)=>{const key=date.toISOString().slice(0,10);const storyDate=dates.find((row)=>day(row.tanggal)===key);const carouselRows=carousels.filter((row)=>day(row.tanggal_posting)===key);return <section className={date.getMonth()!==monthDate.getMonth()?styles.calendarDayMuted:undefined} key={key}><header>{date.getDate()}</header>{storyDate?<button className={styles.calendarTask} onClick={()=>setTab("stories")}>Story: {stories.filter((row)=>String(row.date_id)===String(storyDate.id)).length} slides</button>:null}{carouselRows.map((row)=><button className={styles.calendarEvent} key={String(row.id)} onClick={()=>setTab("carousels")}>{String(row.judul||"Carousel")}</button>)}</section>;})}</div></section>:null}
  {tab==="stories"?<div className={styles.storyPlanner}>{visibleDates.map((dateRow)=>{const slides=stories.filter((row)=>String(row.date_id)===String(dateRow.id)).sort((a,b)=>Number(a.urutan||0)-Number(b.urutan||0));return <section key={String(dateRow.id)}><header><div><strong>{day(dateRow.tanggal)}</strong><span>{slides.length} slide(s)</span></div><button className={String(dateRow.status)==="Done"?styles.adsDecisionActive:undefined} disabled={pending} onClick={()=>startTransition(()=>setStoryPlanStatusAction(String(dateRow.id),dateRow.status==="Done"?"Draft":"Done"))}>{String(dateRow.status||"Draft")}</button></header><div>{slides.map((slide)=><article key={String(slide.id)}>{slide.thumbnail_key?<StorageImage objectKey={String(slide.thumbnail_key)} label={`Slide ${slide.urutan}`}/>:<span>{Number(slide.urutan||0)}</span>}<div><strong>Slide {String(slide.urutan||"-")}</strong><p>{String(slide.isi||"")}</p></div></article>)}</div><details className={styles.createPanel}><summary><i className="ti ti-plus"/> Add slide</summary><form action={addStorySlideAction.bind(null,String(dateRow.id))} className={styles.inlineForm}><input defaultValue={slides.length+1} min="1" name="urutan" type="number"/><textarea name="isi" placeholder="Slide content" required/><button className={styles.primaryButton}>Add</button></form></details></section>;})}<aside><h3>Reusable Story links</h3>{storyLinks.map((row)=><a href={String(row.url)} key={String(row.id)} rel="noreferrer" target="_blank"><strong>{String(row.label)}</strong><span>{String(row.url)}</span></a>)}</aside></div>:null}
  {tab==="carousels"?<div className={styles.carouselPlanner}>{visibleCarousels.map((row)=><article key={String(row.id)}><header><div><span className={styles.dataPill}>{String(row.funnel||"TOFU")}</span><span className={styles.dataPill}>{String(row.status||"Draft")}</span></div><strong>{String(row.judul||"Untitled carousel")}</strong><small>{day(row.tanggal_posting)||"No publish date"}</small></header><dl><div><dt>CTA</dt><dd>{String(row.cta||"-")}</dd></div><div><dt>Brief</dt><dd>{row.link_brief?<a href={String(row.link_brief)} rel="noreferrer" target="_blank">Open brief</a>:"-"}</dd></div></dl><div className={styles.carouselLinks}>{carouselLinks.filter((link)=>String(link.plan_id)===String(row.id)).map((link)=><a href={String(link.url)} key={String(link.id)} rel="noreferrer" target="_blank">{String(link.label)}</a>)}</div><details className={styles.createPanel}><summary>Add reference link</summary><form action={addCarouselPlanLinkAction.bind(null,String(row.id))} className={styles.inlineForm}><input name="label" placeholder="Label" required/><input name="url" placeholder="https://" required type="url"/><button className={styles.primaryButton}>Add</button></form></details></article>)}</div>:null}
  {tab==="directories"?<div className={styles.directoryCards}><Link href="/content-planning/kol"><i className="ti ti-speakerphone"/><strong>KOL directory</strong><span>{kols.length} creators with profile, reach, contact, and rate card.</span></Link><Link href="/content-planning/mt-story"><i className="ti ti-user-star"/><strong>MT Story</strong><span>{mtStories.length} alumni stories, {mtStories.filter((row)=>!row.is_posted).length} pending publication.</span></Link><Link href="/content-planning/cta"><i className="ti ti-click"/><strong>CTA master</strong><span>{ctas.length} reusable Carousel CTA options.</span></Link></div>:null}
  {tab==="manage"?management:null}</div>;
}
