"use client";

import { updatePainPointLabelsAction } from "@/app/actions/customer-knowledge-actions";
import type { ApiRecord } from "@/lib/api/_crud";
import Link from "next/link";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import styles from "../record-manager.module.css";

type Tab = "dashboard" | "database" | "manage";
const stopwords = new Set(["yang","dan","di","ke","dari","itu","ini","gak","ga","gue","aku","kak","dong","sih","ya","aja","bgt","banget","kali","udah","mau","bisa","ada","untuk","dengan","juga","lebih","tapi","kalau","karena","gimana","setelah","pas","waktu","deh","loh","nih"]);
const whitelist = new Set(["mt","hr","hrd","cv","fgd","oa","ip"]);
function labels(row: ApiRecord) { if (Array.isArray(row.labels)) return row.labels.map(String); if (typeof row.labels === "string") { try { const value=JSON.parse(row.labels); return Array.isArray(value)?value.map(String):[]; } catch { return row.labels.split(",").map((item)=>item.trim()).filter(Boolean); } } return []; }
function distribution(rows: ApiRecord[], key: string) { const map=new Map<string,number>(); rows.forEach((row)=>{const value=String(row[key]||"Unknown").trim()||"Unknown";map.set(value,(map.get(value)||0)+1);}); return [...map.entries()].sort((a,b)=>b[1]-a[1]); }

export function CustomerKnowledgeWorkspace({rows,management}:{rows:ApiRecord[];management:ReactNode}){
  const [tab,setTab]=useState<Tab>("dashboard"); const [platform,setPlatform]=useState(""); const [month,setMonth]=useState(""); const [category,setCategory]=useState(""); const [label,setLabel]=useState(""); const [query,setQuery]=useState("");
  const platforms=distribution(rows,"platform").map(([value])=>value); const months=distribution(rows,"bulan").map(([value])=>value); const categories=distribution(rows,"kategori").map(([value])=>value); const allLabels=[...new Set(rows.flatMap(labels))].sort();
  const filtered=useMemo(()=>rows.filter((row)=>(!platform||row.platform===platform)&&(!month||row.bulan===month)&&(!category||row.kategori===category)&&(!label||labels(row).includes(label))&&(!query||`${row.komentar||""} ${row.username||""}`.toLowerCase().includes(query.toLowerCase()))),[rows,platform,month,category,label,query]);
  const keywords=useMemo(()=>{const frequencies=new Map<string,number>(); rows.forEach((row)=>{const words=String(row.komentar||"").toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter((word)=>word&&(whitelist.has(word)||(word.length>2&&!stopwords.has(word))));const seen=new Set(words);for(let index=0;index<words.length-1;index+=1)seen.add(`${words[index]} ${words[index+1]}`);seen.forEach((word)=>{if(word.includes(" ")&&![...rows].some((other)=>other!==row&&String(other.komentar||"").toLowerCase().includes(word)))return;frequencies.set(word,(frequencies.get(word)||0)+1);});});return [...frequencies.entries()].sort((a,b)=>b[1]-a[1]).slice(0,15);},[rows]);
  const byCategory=distribution(rows,"kategori"); const byPlatform=distribution(rows,"platform"); const byMonth=distribution(rows,"bulan");
  return <div className={styles.customerWorkspace}><div className={styles.workspaceHeader}><div><p>Customer knowledge</p><h1>Customer language database</h1><span>Track recurring pain points, customer wording, source platforms, labels, and monthly themes.</span></div><nav className={styles.sectionNav}><Link href="/customer-knowledge/platforms">Platforms</Link><Link href="/customer-knowledge/categories">Categories</Link><Link href="/customer-knowledge/free-class">Free Class</Link></nav></div><nav className={styles.workspaceTabs}>{([['dashboard','Dashboard'],['database','Database'],['manage','Add & manage']] as const).map(([key,value])=><button className={tab===key?styles.workspaceTabActive:styles.workspaceTab} key={key} onClick={()=>setTab(key)}>{value}</button>)}</nav>
  {tab==="dashboard"?<><div className={styles.metricStrip}><div><strong>{rows.length}</strong><span>Total entries</span></div><div><strong>{platforms.length}</strong><span>Platforms</span></div><div><strong>{categories.length}</strong><span>Categories</span></div><div><strong>{allLabels.length}</strong><span>Labels</span></div><div><strong>{months.length}</strong><span>Active months</span></div></div><div className={styles.knowledgeDashboard}><Distribution title="Top categories" rows={byCategory.slice(0,5)}/><section><h3>Top keywords</h3><div className={styles.keywordCloud}>{keywords.map(([word,count],index)=><span key={word} style={{fontSize:`${10+Math.round((keywords.length-index)/Math.max(1,keywords.length)*9)}px`,opacity:.55+(keywords.length-index)/Math.max(1,keywords.length)*.45}} title={`${count} entries`}>{word}</span>)}</div></section><Distribution title="Entries by platform" rows={byPlatform}/><Distribution title="Entries by month" rows={byMonth}/></div></>:null}
  {tab==="database"?<><div className={styles.crmFilters}><input placeholder="Search comment or username" value={query} onChange={(event)=>setQuery(event.target.value)}/><select value={platform} onChange={(event)=>setPlatform(event.target.value)}><option value="">All platforms</option>{platforms.map((value)=><option key={value}>{value}</option>)}</select><select value={month} onChange={(event)=>setMonth(event.target.value)}><option value="">All months</option>{months.map((value)=><option key={value}>{value}</option>)}</select><select value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">All categories</option>{categories.map((value)=><option key={value}>{value}</option>)}</select><select value={label} onChange={(event)=>setLabel(event.target.value)}><option value="">All labels</option>{allLabels.map((value)=><option key={value}>{value}</option>)}</select></div><div className={styles.painPointList}>{filtered.map((row)=><article key={String(row.id)}><details><summary><div><strong>{String(row.komentar||"No comment")}</strong><span>{String(row.username||"Anonymous")} - {String(row.bulan||"No month")}</span></div><i className="ti ti-chevron-down"/></summary><p>{String(row.komentar||"")}</p>{row.source_url?<a href={String(row.source_url)} rel="noreferrer" target="_blank">Open source</a>:null}</details><div className={styles.painPointMeta}><span className={styles.dataPill}>{String(row.platform||"Unknown")}</span><span className={styles.dataPill}>{String(row.kategori||"Unknown")}</span>{labels(row).map((value)=><span className={styles.labelChip} key={value}>{value}</span>)}</div><details className={styles.labelEditor}><summary><i className="ti ti-tags"/> Edit labels</summary><form action={updatePainPointLabelsAction.bind(null,String(row.id))}><fieldset>{allLabels.map((value)=><label key={value}><input defaultChecked={labels(row).includes(value)} name="labels" type="checkbox" value={value}/>{value}</label>)}</fieldset><label><span>New label</span><input name="new_label" placeholder="Create label"/></label><button className={styles.primaryButton}>Save labels</button></form></details></article>)}</div><p className={styles.formMessage}>{filtered.length} of {rows.length} entries</p></>:null}
  {tab==="manage"?management:null}</div>;
}

function Distribution({title,rows}:{title:string;rows:[string,number][]}){const maximum=Math.max(1,...rows.map(([,count])=>count));return <section><h3>{title}</h3>{rows.length?rows.map(([value,count])=><div className={styles.analyticsBar} key={value}><span>{value}</span><i style={{width:`${count/maximum*100}%`}}/><strong>{count}</strong></div>):<p className={styles.formMessage}>No data.</p>}</section>}
