"use client";

import { rescheduleTicketAction } from "@/app/actions/dashboard-actions";
import { updateProgramTaskWorkflowAction } from "@/app/actions/program-actions";
import type { ApiRecord } from "@/lib/api/_crud";
import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import styles from "../record-manager.module.css";

function iso(date: Date) { return date.toISOString().slice(0, 10); }

export function DashboardCalendar({ tickets, tasks, events, referenceDate }: { tickets: ApiRecord[]; tasks: ApiRecord[]; events: ApiRecord[]; referenceDate: string }) {
  const [ticketRows, setTicketRows] = useState(tickets); const [taskRows, setTaskRows] = useState(tasks); const [monthOffset, setMonthOffset] = useState(0); const [pending, startTransition] = useTransition();
  const calendar = useMemo(() => { const base = new Date(referenceDate); const first = new Date(base.getFullYear(), base.getMonth() + monthOffset, 1, 12); const start = new Date(first); start.setDate(1 - first.getDay()); return { month: first.getMonth(), label: first.toLocaleDateString("en", { month: "long", year: "numeric" }), days: Array.from({ length: 42 }, (_, index) => { const value = new Date(start); value.setDate(start.getDate() + index); return value; }) }; }, [referenceDate, monthOffset]);
  function drop(payload: string, date: string) { if (!payload) return; const [kind,id] = payload.split(":"); if (kind === "ticket") { const before = ticketRows; setTicketRows((current) => current.map((item) => String(item.id) === id ? { ...item, due_date: date } : item)); startTransition(async () => { try { await rescheduleTicketAction(id,date); } catch { setTicketRows(before); } }); } else if (kind === "task") { const before = taskRows; setTaskRows((current) => current.map((item) => String(item.id) === id ? { ...item, due_date: date } : item)); startTransition(async () => { try { await updateProgramTaskWorkflowAction(id,{ dueDate: date }); } catch { setTaskRows(before); } }); } }
  const upcoming = [...taskRows.filter((item) => item.status !== "Done").map((item) => ({ id: String(item.id), title: String(item.title || "Untitled"), kind: "Task", date: item.due_date, href: "/program/tasks" })), ...ticketRows.filter((item) => item.status !== "Done").map((item) => ({ id: String(item.id), title: String(item.title || "Untitled"), kind: "Ticket", date: item.due_date, href: "/tickets" }))].filter((item) => item.date).sort((a,b) => String(a.date).localeCompare(String(b.date))).slice(0,12);
  return <div className={styles.dashboardOps}><div className={styles.calendarToolbar}><div><strong>Operations calendar · {calendar.label}</strong><span>Programs, tasks, and tickets. Drag tasks or tickets to reschedule.</span></div><div><button onClick={() => setMonthOffset((value) => value - 1)}><i className="ti ti-chevron-left" /></button><button onClick={() => setMonthOffset(0)}>Today</button><button onClick={() => setMonthOffset((value) => value + 1)}><i className="ti ti-chevron-right" /></button></div>{pending ? <span>Saving...</span> : null}</div><div className={styles.monthCalendar}>{calendar.days.map((day) => { const key = iso(day); const muted = day.getMonth() !== calendar.month; return <section className={muted ? styles.calendarDayMuted : undefined} key={key} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event.dataTransfer.getData("calendar-item"),key)}><header>{day.getDate()}</header>{events.filter((item) => String(item.tanggal || "").slice(0,10) === key).map((item) => <Link className={styles.calendarEvent} href="/program" key={String(item.id)}>{String(item.nama || "Program")}</Link>)}{taskRows.filter((item) => String(item.due_date || "").slice(0,10) === key).map((item) => <Link className={styles.calendarTask} draggable href="/program/tasks" key={String(item.id)} onDragStart={(event) => event.dataTransfer.setData("calendar-item",`task:${item.id}`)}>{String(item.title || "Task")}</Link>)}{ticketRows.filter((item) => String(item.due_date || "").slice(0,10) === key).map((item) => <Link className={styles.calendarTicket} draggable href={`/tickets#${item.id}`} key={String(item.id)} onDragStart={(event) => event.dataTransfer.setData("calendar-item",`ticket:${item.id}`)}>{String(item.title || "Ticket")}</Link>)}</section>; })}</div><div className={styles.dashboardLists}><section><header><strong>Upcoming work</strong><span>{upcoming.length}</span></header>{upcoming.map((item,index) => <Link href={String(item.href)} key={`${item.kind}-${item.id}-${index}`}><strong>{String(item.title || "Untitled")}</strong><span>{item.kind} · {String(item.date)}</span></Link>)}</section><section><header><strong>Upcoming programs</strong><Link href="/program">View all</Link></header>{events.filter((event) => !["Done","Cancelled"].includes(String(event.status))).sort((a,b) => String(a.tanggal || "9999").localeCompare(String(b.tanggal || "9999"))).slice(0,8).map((event) => <Link href="/program" key={String(event.id)}><strong>{String(event.nama || "Untitled")}</strong><span>{String(event.tanggal || "No date")}</span></Link>)}</section></div></div>;
}
