"use client";

import type { ApiRecord } from "@/lib/api/_crud";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import styles from "../record-manager.module.css";

const ratingFields = ["materi_judul", "materi_kebutuhan", "materi_mudah", "materi_jawab", "nara_kuasai", "nara_jelas", "kualitas_teknis", "waktu", "moderator", "info_webinar", "kepuasan", "minat", "rekomendasi"];

export function FreeClassTools({ rows }: { rows: ApiRecord[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const analytics = useMemo(() => { const values = ratingFields.flatMap((field) => rows.map((row) => Number(row[field])).filter((value) => value >= 1 && value <= 5)); const average = values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; const series = new Map<string, number>(); rows.forEach((row) => series.set(String(row.seri || "Unknown"), (series.get(String(row.seri || "Unknown")) || 0) + 1)); return { average, series: [...series.entries()].sort((a, b) => b[1] - a[1]) }; }, [rows]);
  async function importRows(formData: FormData) { setBusy(true); setMessage(""); try { const response = await fetch("/api/free-class/import", { method: "POST", body: formData }); const result = await response.json() as { imported?: number; error?: string }; if (!response.ok) throw new Error(result.error || "Import failed."); setMessage(`Imported ${result.imported || 0} evaluation(s).`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import failed."); } finally { setBusy(false); } }
  return <div className={styles.toolStack}><div className={styles.metricStrip}><div><strong>{rows.length}</strong><span>respondents</span></div><div><strong>{analytics.average.toFixed(2)}</strong><span>average rating</span></div><div><strong>{analytics.series.length}</strong><span>class series</span></div><div><strong>{rows.filter((row) => Number(row.rekomendasi) >= 4).length}</strong><span>promoters</span></div></div><details className={styles.createPanel}><summary><i className="ti ti-file-import" /> Import survey responses</summary><form action={importRows} className={styles.toolForm}><label>Public Google Sheets URL<input name="url" placeholder="https://docs.google.com/spreadsheets/d/..." type="url" /></label><span>or upload a CSV/XLSX file</span><input accept=".csv,.xlsx" name="file" type="file" /><button className={styles.primaryButton} disabled={busy}>Import</button></form></details>{message ? <p className={styles.formMessage}>{message}</p> : null}<div className={styles.summaryGrid}>{analytics.series.map(([series, count]) => { const seriesRows = rows.filter((row) => String(row.seri || "Unknown") === series); const scores = seriesRows.flatMap((row) => ratingFields.map((field) => Number(row[field])).filter((value) => value >= 1 && value <= 5)); const average = scores.length ? scores.reduce((sum, value) => sum + value, 0) / scores.length : 0; return <article key={series}><header><strong>{series}</strong><span>{average.toFixed(2)}</span></header><p>{count} respondent(s)</p><footer><span>{seriesRows.filter((row) => row.hal_baik).length} positive comments</span><span>{seriesRows.filter((row) => row.ditingkatkan).length} improvements</span></footer></article>; })}</div></div>;
}
