"use client";

import type { ApiRecord } from "@/lib/api/_crud";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import styles from "../record-manager.module.css";

function numeric(value: unknown) { const result = Number(value || 0); return Number.isFinite(result) ? result : 0; }

export function InstagramTools({ snapshots, targets, referenceDate }: { snapshots: ApiRecord[]; targets: ApiRecord[]; referenceDate: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const analytics = useMemo(() => { const now = new Date(referenceDate); const sorted = [...snapshots].sort((a, b) => String(a.week_start).localeCompare(String(b.week_start))); const latest = sorted.at(-1); const earliest = sorted[0]; const days = latest && earliest ? Math.max(1, (new Date(String(latest.week_start)).getTime() - new Date(String(earliest.week_start)).getTime()) / 86400000) : 1; const growth = numeric(latest?.followers_total) - numeric(earliest?.followers_total); const dailyGrowth = growth / days; const daysToYearEnd = Math.max(0, (new Date(now.getFullYear(), 11, 31).getTime() - now.getTime()) / 86400000); const predicted = Math.round(numeric(latest?.followers_total) + dailyGrowth * daysToYearEnd); const target = targets.find((item) => numeric(item.year) === now.getFullYear()) || targets.at(-1); const engagement = latest && numeric(latest.reach) ? numeric(latest.interactions) / numeric(latest.reach) * 100 : 0; return { sorted, latest, growth, dailyGrowth, predicted, target: numeric(target?.target_followers), engagement }; }, [snapshots, targets, referenceDate]);
  async function importSnapshots(formData: FormData) { setBusy(true); setMessage(""); try { const response = await fetch("/api/instagram/import", { method: "POST", body: formData }); const result = await response.json() as { imported?: number; error?: string }; if (!response.ok) throw new Error(result.error || "Import failed."); setMessage(`Imported ${result.imported || 0} weekly snapshot(s).`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import failed."); } finally { setBusy(false); } }
  return <div className={styles.toolStack}><div className={styles.metricStrip}><div><strong>{numeric(analytics.latest?.followers_total).toLocaleString()}</strong><span>followers</span></div><div><strong>{analytics.growth.toLocaleString()}</strong><span>tracked growth</span></div><div><strong>{analytics.dailyGrowth.toFixed(1)}</strong><span>followers per day</span></div><div><strong>{analytics.engagement.toFixed(2)}%</strong><span>latest engagement</span></div><div><strong>{analytics.predicted.toLocaleString()}</strong><span>year-end projection</span></div></div><details className={styles.createPanel}><summary><i className="ti ti-file-import" /> Import weekly snapshots</summary><form action={importSnapshots} className={styles.toolForm}><input accept=".csv,.xlsx" name="file" type="file" required /><button className={styles.primaryButton} disabled={busy}>Import</button></form></details>{message ? <p className={styles.formMessage}>{message}</p> : null}<div className={styles.progressPanel}><div><strong>Annual target</strong><span>{analytics.target ? `${numeric(analytics.latest?.followers_total).toLocaleString()} / ${analytics.target.toLocaleString()}` : "No target configured"}</span></div><progress max={Math.max(analytics.target, 1)} value={Math.min(numeric(analytics.latest?.followers_total), Math.max(analytics.target, 1))} /></div><div className={styles.timelineList}>{[...analytics.sorted].reverse().slice(0, 12).map((row) => <div key={String(row.id)}><strong>{String(row.week_start || "-")}</strong><span>{numeric(row.followers_total).toLocaleString()} followers</span><span>{numeric(row.reach).toLocaleString()} reach</span></div>)}</div></div>;
}
