"use client";

import type { ApiRecord } from "@/lib/api/_crud";
import Link from "next/link";
import { useRouter } from "next/navigation";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import styles from "../record-manager.module.css";

type Tab="dashboard"|"list"|"newsletter"|"company"|"manage";
const monthNames=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
function list(value:unknown){if(Array.isArray(value))return value.map(String);if(typeof value==="string"){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.map(String);}catch{}return value.split(/[;,|]/).map((item)=>item.trim()).filter(Boolean);}return[];}
function date(value:unknown){const parsed=new Date(String(value||""));return Number.isFinite(parsed.getTime())?parsed:null;}
function week(value:Date){return value.getDate()<=7?1:value.getDate()<=14?2:value.getDate()<=21?3:4;}
function frequency(rows:ApiRecord[],key:string){const map=new Map<string,number>();rows.forEach((row)=>{const value=String(row[key]||"Unknown");map.set(value,(map.get(value)||0)+1);});return [...map.entries()].sort((a,b)=>b[1]-a[1]);}

export function MtVacancyTools({rows,referenceDate,management}:{rows:ApiRecord[];referenceDate:string;management:ReactNode}){
  const now=useMemo(()=>new Date(referenceDate),[referenceDate]);const router=useRouter();const [tab,setTab]=useState<Tab>("dashboard");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [query,setQuery]=useState("");const [industry,setIndustry]=useState("");const [month,setMonth]=useState("");const [year,setYear]=useState("");const [nlMonth,setNlMonth]=useState(now.getMonth());const [nlYear,setNlYear]=useState(now.getFullYear());const [nlWeek,setNlWeek]=useState(week(now));const [nlIndustries,setNlIndustries]=useState<string[]>([]);const [output,setOutput]=useState<"wa"|"email">("wa");
  const industries=frequency(rows,"industry").map(([value])=>value);const years=[...new Set(rows.map((row)=>String(row.year||"")).filter(Boolean))].sort().reverse();
  const active=useMemo(()=>rows.filter((row)=>String(row.status||"Active").toLowerCase()!=="closed"&&(!date(row.deadline)||date(row.deadline)!.getTime()>=now.getTime())),[rows,now]);
  const filtered=useMemo(()=>rows.filter((row)=>(!query||`${row.company||""} ${row.program||""}`.toLowerCase().includes(query.toLowerCase()))&&(!industry||row.industry===industry)&&(!year||String(row.year)===year)&&(!month||list(row.months).map(Number).includes(Number(month)))),[rows,query,industry,year,month]);
  const monthly=Array.from({length:12},(_,index)=>rows.filter((row)=>String(row.year)===String(now.getFullYear())&&list(row.months).map(Number).includes(index+1)).length);const industryDist=frequency(rows,"industry");const thisWeek=rows.filter((row)=>{const created=date(row.created_at);return created&&Math.abs(now.getTime()-created.getTime())<=7*86400000;}).length;const thisMonth=rows.filter((row)=>list(row.months).map(Number).includes(now.getMonth()+1)&&String(row.year)===String(now.getFullYear())).length;
  const newsletterRows=rows.filter((row)=>{const created=date(row.created_at);return created&&created.getMonth()===nlMonth&&created.getFullYear()===nlYear&&week(created)===nlWeek&&list(row.months).map(Number).includes(nlMonth+1)&&(!nlIndustries.length||nlIndustries.includes(String(row.industry)));});
  const newsletter=buildNewsletter(newsletterRows,nlMonth,nlWeek,nlIndustries);
  const companies=useMemo(()=>{const map=new Map<string,{industry:string;programs:Map<string,ApiRecord[]>}>();rows.forEach((row)=>{const name=String(row.company||"Unknown");const item=map.get(name)||{industry:String(row.industry||"Unknown"),programs:new Map()};const program=String(row.program||"Untitled");item.programs.set(program,[...(item.programs.get(program)||[]),row]);map.set(name,item);});return[...map.entries()].sort(([a],[b])=>a.localeCompare(b));},[rows]);
  async function importVacancies(formData:FormData){setBusy(true);setMessage("");try{const response=await fetch("/api/mt-vacancies/import",{method:"POST",body:formData});const result=await response.json() as {inserted?:number;updated?:number;error?:string};if(!response.ok)throw new Error(result.error||"Import failed.");setMessage(`Imported ${result.inserted||0}; updated ${result.updated||0}.`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Import failed.");}finally{setBusy(false);}}
  function copy(){navigator.clipboard.writeText(newsletter[output]).then(()=>setMessage(`${output.toUpperCase()} newsletter copied.`)).catch(()=>setMessage("Clipboard access was blocked."));}
  return <div className={styles.vacancyWorkspace}><div className={styles.workspaceHeader}><div><p>Talent</p><h1>Management Trainee vacancies</h1><span>Vacancy calendar, customer newsletter, and historical company opening patterns.</span></div><Link className={styles.secondaryButton} href="/job-vacancy-mt/industries"><i className="ti ti-database"/> Industry master</Link></div><nav className={styles.workspaceTabs}>{([['dashboard','Dashboard'],['list','All vacancies'],['newsletter','Newsletter'],['company','Company Intel'],['manage','Add & manage']] as const).map(([key,label])=><button className={tab===key?styles.workspaceTabActive:styles.workspaceTab} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  {tab==="dashboard"?<><div className={styles.metricStrip}><div><strong>{rows.length}</strong><span>Total vacancies</span></div><div><strong>{thisWeek}</strong><span>Added this week</span></div><div><strong>{industryDist[0]?.[0]||"-"}</strong><span>Top industry</span></div><div><strong>{thisMonth}</strong><span>Open this month</span></div><div><strong>{active.length}</strong><span>Active now</span></div></div><div className={styles.analyticsGrid}><section><h3>Vacancies open by month - {now.getFullYear()}</h3>{monthly.map((value,index)=><div className={styles.analyticsBar} key={monthNames[index]}><span>{monthNames[index]}</span><i style={{width:`${value/Math.max(1,...monthly)*100}%`}}/><strong>{value}</strong></div>)}</section><section><h3>Industry distribution</h3>{industryDist.map(([value,count])=><div className={styles.analyticsBar} key={value}><span>{value}</span><i style={{width:`${count/Math.max(1,industryDist[0]?.[1]||1)*100}%`}}/><strong>{count}</strong></div>)}</section></div><div className={styles.summaryGrid}>{industryDist.map(([value,count])=><article key={value}><header><strong>{value}</strong><span>{count}</span></header><p>{new Set(rows.filter((row)=>row.industry===value).map((row)=>String(row.company))).size} companies</p><footer><span>{rows.filter((row)=>row.industry===value&&list(row.months).map(Number).includes(now.getMonth()+1)).length} open this month</span></footer></article>)}</div></>:null}
  {tab==="list"?<><div className={styles.crmFilters}><input placeholder="Search company or program" value={query} onChange={(event)=>setQuery(event.target.value)}/><select value={industry} onChange={(event)=>setIndustry(event.target.value)}><option value="">All industries</option>{industries.map((value)=><option key={value}>{value}</option>)}</select><select value={month} onChange={(event)=>setMonth(event.target.value)}><option value="">All opening months</option>{monthNames.map((value,index)=><option key={value} value={index+1}>{value}</option>)}</select><select value={year} onChange={(event)=>setYear(event.target.value)}><option value="">All years</option>{years.map((value)=><option key={value}>{value}</option>)}</select></div><VacancyTable rows={filtered}/></>:null}
  {tab==="newsletter"?<section className={styles.newsletterPanel}><header><h2>Newsletter generator</h2><p>Filters by input week and includes only customer-facing career links.</p></header><div className={styles.crmFilters}><select value={nlMonth} onChange={(event)=>setNlMonth(Number(event.target.value))}>{monthNames.map((value,index)=><option key={value} value={index}>{value}</option>)}</select><input min="2024" type="number" value={nlYear} onChange={(event)=>setNlYear(Number(event.target.value))}/><select value={nlWeek} onChange={(event)=>setNlWeek(Number(event.target.value))}>{[1,2,3,4].map((value)=><option key={value} value={value}>Week {value}</option>)}</select><details className={styles.multiFilter}><summary>{nlIndustries.length?`${nlIndustries.length} industries`:"All industries"}</summary>{industries.map((value)=><label key={value}><input checked={nlIndustries.includes(value)} onChange={()=>setNlIndustries((current)=>current.includes(value)?current.filter((item)=>item!==value):[...current,value])} type="checkbox"/>{value}</label>)}</details></div>{newsletterRows.length?<><nav className={styles.workspaceTabs}><button className={output==="wa"?styles.workspaceTabActive:styles.workspaceTab} onClick={()=>setOutput("wa")}>WhatsApp</button><button className={output==="email"?styles.workspaceTabActive:styles.workspaceTab} onClick={()=>setOutput("email")}>Email</button></nav><pre>{newsletter[output]}</pre><button className={styles.secondaryButton} onClick={copy}><i className="ti ti-copy"/> Copy text</button></>:<div className={styles.emptyState}><i className="ti ti-calendar-off"/><strong>No matching vacancies</strong><span>Change the week or industry selection.</span></div>}</section>:null}
  {tab==="company"?<><div className={styles.filterBar}><input placeholder="Search company or program" value={query} onChange={(event)=>setQuery(event.target.value)}/><select value={industry} onChange={(event)=>setIndustry(event.target.value)}><option value="">All industries</option>{industries.map((value)=><option key={value}>{value}</option>)}</select></div><div className={styles.companyIntel}>{companies.filter(([company,item])=>(!query||`${company} ${[...item.programs.keys()].join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!industry||item.industry===industry)).map(([company,item])=><article key={company}><header><div><strong>{company}</strong><span>{item.industry} - {item.programs.size} program(s)</span></div></header>{[...item.programs.entries()].map(([program,history])=>{const patterns=history.map((row)=>list(row.months).map(Number).sort((a,b)=>a-b).join(","));const changed=patterns.some((value)=>value!==patterns[0]);return <section key={program}><h3>{program}{changed?<span className={styles.partialBadge}>Pattern changed</span>:null}</h3>{[...history].sort((a,b)=>String(a.year).localeCompare(String(b.year))).map((row)=><div key={String(row.id)}><strong>{String(row.year||"-")}</strong><span>{list(row.months).map((value)=>monthNames[Number(value)-1]).filter(Boolean).join(", ")||"-"}</span><span className={styles.dataPill}>{String(row.status||"-")}</span></div>)}</section>})}</article>)}</div></>:null}
  {tab==="manage"?<><details className={styles.createPanel}><summary><i className="ti ti-file-import"/> Import vacancy CSV/XLSX</summary><form action={importVacancies} className={styles.toolForm}><input accept=".csv,.xlsx" name="file" required type="file"/><button className={styles.primaryButton} disabled={busy}>Import</button></form></details>{message?<p className={styles.formMessage}>{message}</p>:null}{management}</>:null}</div>;
}

function VacancyTable({rows}:{rows:ApiRecord[]}){return <div className={styles.dataPanel}><div className={styles.tableScroll}><table><thead><tr><th>Company / Program</th><th>Industry</th><th>Roles</th><th>Open months</th><th>Deadline</th><th>Career links</th></tr></thead><tbody>{rows.map((row)=><tr key={String(row.id)}><td><strong>{String(row.company||"-")}</strong><br/><span>{String(row.program||"-")}</span></td><td><span className={styles.dataPill}>{String(row.industry||"-")}</span></td><td>{list(row.roles).join(", ")||"-"}</td><td>{list(row.months).map((value)=>monthNames[Number(value)-1]).filter(Boolean).join(", ")||"-"} {String(row.year||"")}</td><td>{String(row.deadline||"Open")}</td><td>{list(row.career_links).map((value,index)=><a href={value} key={value} rel="noreferrer" target="_blank">Link {index+1}</a>)}</td></tr>)}</tbody></table></div></div>}
function buildNewsletter(rows:ApiRecord[],month:number,selectedWeek:number,industries:string[]){const monthLabel=monthNames[month];const industry=industries.length?` ${industries.join(", ")}`:"";const waRows=rows.map((row,index)=>`*${index+1}. ${row.company} - ${row.program}*\nRoles: ${list(row.roles).join(", ")||"-"}\n${list(row.selection).length?`Selection: ${list(row.selection).join(" -> ")}\n`:""}${list(row.career_links).map((link)=>`Link: ${link}`).join("\n")}`).join("\n\n");const emailRows=rows.map((row,index)=>`${index+1}. ${String(row.company).toUpperCase()}\n   Program: ${row.program}\n   Role: ${list(row.roles).join(", ")||"-"}\n${list(row.selection).length?`   Selection: ${list(row.selection).join(" -> ")}\n`:""}${list(row.career_links).map((link)=>`   Link: ${link}`).join("\n")}`).join("\n--------------------------\n");return{wa:`Halo!\n\nUpdate MT ${monthLabel}, week ${selectedWeek}.\nThere are *${rows.length} new MT vacancies${industry}*.\n\n${waRows}\n\nSee CareerCclub resources at careercclub.com`,email:`Subject: [MT Alert] ${rows.length} New MT Vacancies - ${monthLabel} Week ${selectedWeek}\n\nHello,\n\nHere are this week's MT openings${industry}:\n\n${emailRows}\n\nApplication resources: careercclub.com\n\nCareerCclub Team`};}
