"use client";

import { reorderResourcesAction } from "@/app/actions/resource-actions";
import type { ApiRecord } from "@/lib/api/_crud";
import { useMemo, useState, useTransition } from "react";
import styles from "../record-manager.module.css";

export function ResourceTools({rows}:{rows:ApiRecord[]}){
  const [items,setItems]=useState([...rows].sort((a,b)=>String(a.kategori).localeCompare(String(b.kategori))||Number(a.urutan||0)-Number(b.urutan||0)));const [query,setQuery]=useState("");const [revealed,setRevealed]=useState<Set<string>>(new Set());const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();
  const visible=useMemo(()=>items.filter((row)=>!query||`${row.kategori} ${row.nama} ${row.url} ${row.email} ${row.username}`.toLowerCase().includes(query.toLowerCase())),[items,query]);const groups=[...new Set(visible.map((row)=>String(row.kategori||"Other")))];
  function move(id:string,direction:-1|1){const index=items.findIndex((item)=>String(item.id)===id);const peers=items.map((item,position)=>({item,position})).filter(({item})=>item.kategori===items[index]?.kategori);const peerIndex=peers.findIndex(({position})=>position===index);const target=peers[peerIndex+direction]?.position;if(index<0||target===undefined)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];setItems(next);startTransition(()=>reorderResourcesAction(next.map((row,position)=>({id:String(row.id),kategori:String(row.kategori||"Other"),urutan:position}))));}
  function copy(label:string,value:unknown){navigator.clipboard.writeText(String(value||"")).then(()=>setMessage(`${label} copied.`)).catch(()=>setMessage("Clipboard access was blocked."));}
  return <div className={styles.toolStack}><div className={styles.filterBar}><input placeholder="Search resources" value={query} onChange={(event)=>setQuery(event.target.value)}/>{pending?<span className={styles.formMessage}>Saving order...</span>:message?<span className={styles.formMessage}>{message}</span>:null}</div><div className={styles.resourceGroups}>{groups.map((group)=><section key={group}><header><div><i className="ti ti-folder"/><strong>{group}</strong></div><span>{visible.filter((row)=>String(row.kategori||"Other")===group).length} items</span></header><div>{visible.filter((row)=>String(row.kategori||"Other")===group).map((row)=>{const id=String(row.id);const credential=row.tipe==="credential";const show=revealed.has(id);return <article key={id}><div className={styles.resourceTitle}><i className={`ti ti-${credential?"key":"link"}`}/><div><strong>{String(row.nama||"Untitled")}</strong><span>{credential?"Credential":"Link"}</span></div></div>{credential?<div className={styles.credentialFields}>{[["Email",row.email],["Username",row.username],["Password",row.password]].filter(([,value])=>value).map(([label,value])=><div key={String(label)}><span>{label}</span><code>{label==="Password"&&!show?"••••••••":String(value)}</code><button aria-label={`Copy ${label}`} onClick={()=>copy(String(label),value)}><i className="ti ti-copy"/></button></div>)}</div>:<div className={styles.resourceLink}><a href={String(row.url||"#")} rel="noreferrer" target="_blank">{String(row.url||"No URL")}</a><button onClick={()=>copy("URL",row.url)}><i className="ti ti-copy"/></button></div>}<footer>{credential?<button onClick={()=>setRevealed((current)=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;})}><i className={`ti ti-eye${show?"-off":""}`}/> {show?"Hide":"Reveal"}</button>:null}<button onClick={()=>move(id,-1)} aria-label="Move up"><i className="ti ti-chevron-up"/></button><button onClick={()=>move(id,1)} aria-label="Move down"><i className="ti ti-chevron-down"/></button></footer></article>;})}</div></section>)}</div></div>;
}
