import { createUserAction, updateUserAccessAction } from "@/app/actions/user-actions";
import type { AuthUserRecord } from "@/lib/api/auth-users";
import styles from "../record-manager.module.css";

type SafeUser = Pick<AuthUserRecord, "id" | "email" | "name" | "role" | "is_active" | "created_at">;

export function UserManagement({ users }: { users: SafeUser[] }) {
  return <div className="grid gap-3.5"><p className="text-[11px] text-muted-foreground">Manage Auth.js credentials and access roles. Password hashes are never sent to the browser. <strong>{users.length}</strong> users.</p><details className={styles.createPanel}><summary><i className="ti ti-user-plus" /> Add user</summary><form action={createUserAction} className={styles.formGrid}><label className={styles.field}><span>Name</span><input name="name" required /></label><label className={styles.field}><span>Email</span><input name="email" type="email" required /></label><label className={styles.field}><span>Role</span><input name="role" defaultValue="member" required /></label><label className={styles.field}><span>Temporary password</span><input name="password" type="password" minLength={12} required /></label><button className={styles.primaryButton}>Create user</button></form></details><div className={styles.userGrid}>{users.map((user) => <form action={updateUserAccessAction.bind(null, String(user.id))} key={String(user.id)}><header><strong>{user.name || user.email}</strong><span>{user.email}</span></header><label className={styles.field}><span>Role</span><input name="role" defaultValue={user.role || "member"} /></label><label className={styles.checkField}><input name="is_active" type="checkbox" defaultChecked={user.is_active !== false} /><span>Active</span></label><label className={styles.field}><span>New password (optional)</span><input name="password" type="password" minLength={12} /></label><button className={styles.secondaryButton}>Save</button></form>)}</div></div>;
}
